name: test

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  test1:
    name: job2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: pwd
        run: |
          pwd
          mkdir app
      - name: pwd
        run: pwd
      - name: cd
        run: |
          cd app
          touch hello.txt
          pwd
      - name: pwd
        run: pwd
      - name: pwd
        run: pwd
      - name: ls
        run: ls
