name: test

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  test1:
    name: job2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: pwd
        run: |
          pwd
          mkdir app
      - name: pwd
        run: pwd
      - name: cd
        run: |
          cd app
          pwd
      - name: pwd
        run: pwd

  test2:
    name: pwpr-with-playwright-install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run pwpr
        run: |
          npx playwright install
          npx pwpr@latest --url https://opentermsarchive.org --locale fr-FR | grep -o "Access\w*"
  
  test3:
    name: pwpr-default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run pwpr
        run: |
          npx pwpr --url https://opentermsarchive.org --locale fr-FR | grep -o "Access\w*"
          
  test4:
    name: pwpr-clear-npx-cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run pwpr
        run: |
          npx clear-npx-cache
          npx pwpr --url https://opentermsarchive.org --locale fr-FR | grep -o "Access\w*"
    
    
  test5:
    name: pwpr-old
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run pwpr
        run: |
          npx pwpr@2.2.0 --url https://opentermsarchive.org --locale fr-FR | grep -o "Access\w*"
  
  test6:
    name: pwpr-with-clear-and-playwright-install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run pwpr
        run: |
          npx clear-npx-cache
          npx playwright install
          npx pwpr@latest --url https://opentermsarchive.org --locale fr-FR | grep -o "Access\w*"
  
  test7:
    name: pwpr-node-14
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Run pwpr
        run: |
          npx clear-npx-cache
          npx pwpr --url https://opentermsarchive.org --locale fr-FR | grep -o "Access\w*"
    
     
